apiVersion: v2
name: k8s-cert-manager
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.0-replaceme

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.0-replaceme"
dependencies:
  - name: cert-manager
    version: v1.13.1
    repository: https://charts.jetstack.io
    alias: cert-manager
    condition: cert-manager.enabled
annotations:
  # Dependency for the cert-manager-CRDs.
  # Allow all versions up to next major version to avoid breaking changes
  "k8s.cloudogu.com/ces-dependency/k8s-cert-manager-crd": "1.x.x-0"
